### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by giosooul** [fdmomtaz/WeightTracker-DotNetMaui#1]
Hello,
I cannot build the project using VS 2022 and .NET 8.0, during the build I run into the following error :
```
Could not find Android Resource '@styleable/SKCanvasView'. Please update @(AndroidResource) to add the missing resource.	
Could not find Android Resource '@styleable/SKCanvasView_ignorePixelScaling'. Please update @(AndroidResource) to add the missing resource.
```

**Comment by fdmomtaz** [comment]
Hi @giosooul 

Thanks for reporting this issue. Looks like a known issue with MAUI. 

https://github.com/dotnet/maui/issues/19645

I can’t reproduce it on my machine; however, there are some solutions in the MAUI issue. I’ll make the changes and push them to a branch to see if they would fix the issue for you.

Thanks

**Comment by fdmomtaz** [comment]
Hi @giosooul 

Added a possible fix from the mentioned issue to [`bugfix/androidBuild`](https://github.com/fdmomtaz/WeightTracker-DotNetMaui/tree/bugfix/androidBuild) branch. Can you please check It out and lemme know if it works?

Thanks

**Comment by DPonder15** [comment]
Not OP, but I had this same issue. @fdmomtaz Your fix is a partial one, and what finally worked for me is [this](https://github.com/dotnet/maui/issues/19645#issuecomment-1924235196).

Edit: You should also make sure that the Build Action for the "attrs.xml" file is set to "AndroidResource". If you do this, you may not even need to perform the removal of the added `<declare-styleable>` element.

**Comment by fdmomtaz** [comment]
@DPonder15 Thanks for testing out the fix and letting me know what worked for you. 

Can you please add a pull request with the needed change? If not, I can make the change in the link and push it out to be tested.

**Comment by DPonder15** [comment]
@fdmomtaz After further review, I found that updating the XML file to the Build Action "AndroidResource" through the VS Properties UI results in the XML file being updated to the Build Action "None" when inspecting the git changes made to the CSPROJ file.

Your change seems to result in the Build Action "AndroidResource" automatically being applied in the CSPROJ but that the "Remove" attribute is applied instead of "Include". Here is the XML file addition as it exists in your [bugfix/androidBuild](https://github.com/fdmomtaz/WeightTracker-DotNetMaui/tree/bugfix/androidBuild) branch:

`
<ItemGroup>
  <AndroidResource Remove="Platforms\Android\Resources\values\attrs.xml" />
</ItemGroup>
`

And needs to be updated to:

`
<ItemGroup>
	<AndroidResource Include="Platforms/Android/Resources/values/attrs.xml" />
</ItemGroup>
`

I didn't have permission to make the change myself and push to a PR, so you will need to go ahead and make the change yourself.

**Comment by fdmomtaz** [comment]
@DPonder15 Thanks for following up and good catch, I forgot to include the file in the project... using the VSCode given I'm on Mac and the support is not as good as the full VS.

Fixed the issue and did a merge to master 👍
